from highway_env.envs.highway_env_0 import *
from highway_env.envs.highway_env_1 import *
from highway_env.envs.highway_env_2 import *
from highway_env.envs.highway_env_3 import *
from highway_env.envs.highway_env_4 import *
from highway_env.envs.highway_env_5 import *
from highway_env.envs.highway_env_6 import *
from highway_env.envs.highway_env_7 import *
from highway_env.envs.highway_env_8 import *
from highway_env.envs.highway_env_9 import *